"""The Open-Meteo Marine Weather integration.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""

from __future__ import annotations

from homeassistant.config_entries import ConfigEntry
from homeassistant.const import Platform
from homeassistant.core import HomeAssistant

from .coordinator import MarineWeatherCoordinator

PLATFORMS: list[Platform] = [Platform.SENSOR]

type MarineWeatherConfigEntry = ConfigEntry[MarineWeatherCoordinator]


async def async_setup_entry(
    hass: HomeAssistant, entry: MarineWeatherConfigEntry
) -> bool:
    """Set up Open-Meteo Marine Weather from a config entry."""
    coordinator = MarineWeatherCoordinator(hass, entry)
    await coordinator.async_config_entry_first_refresh()

    entry.runtime_data = coordinator

    await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)
    return True


async def async_unload_entry(
    hass: HomeAssistant, entry: MarineWeatherConfigEntry
) -> bool:
    """Unload a config entry."""
    return await hass.config_entries.async_unload_platforms(entry, PLATFORMS)
