"""The Open-Meteo Marine Weather integration.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""

from __future__ import annotations

from homeassistant.config_entries import ConfigEntry
from homeassistant.const import Platform
from homeassistant.core import HomeAssistant

from .const import CONF_ENABLED_SENSORS
from .coordinator import MarineWeatherCoordinator

PLATFORMS: list[Platform] = [Platform.SENSOR, Platform.BINARY_SENSOR]

type MarineWeatherConfigEntry = ConfigEntry[MarineWeatherCoordinator]


async def async_setup_entry(
    hass: HomeAssistant, entry: MarineWeatherConfigEntry
) -> bool:
    """Set up Open-Meteo Marine Weather from a config entry."""
    coordinator = MarineWeatherCoordinator(hass, entry)
    await coordinator.async_config_entry_first_refresh()

    entry.runtime_data = coordinator

    # Reload the entry when surf-quality thresholds are changed via the
    # options flow, so entities pick up the new values immediately.
    entry.async_on_unload(entry.add_update_listener(_async_update_listener))

    await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)
    return True


async def _async_update_listener(
    hass: HomeAssistant, entry: MarineWeatherConfigEntry
) -> None:
    """Reload the config entry when its options change."""
    await hass.config_entries.async_reload(entry.entry_id)


async def async_unload_entry(
    hass: HomeAssistant, entry: MarineWeatherConfigEntry
) -> bool:
    """Unload a config entry."""
    return await hass.config_entries.async_unload_platforms(entry, PLATFORMS)


async def async_migrate_entry(
    hass: HomeAssistant, entry: MarineWeatherConfigEntry
) -> bool:
    """Migrate an old config entry to the current schema."""
    if entry.version > 1:
        # Written by a newer release than this one; refuse rather than guess.
        return False

    if entry.minor_version < 2:
        # Imported here rather than at module scope because sensor.py imports
        # MarineWeatherConfigEntry from this module.
        from .sensor import PREVIOUS_DEFAULT_SENSOR_KEYS, SENSOR_DESCRIPTIONS

        stored = entry.data.get(CONF_ENABLED_SENSORS)

        # Minor version 1 kept no record of whether the stored sensor list was
        # a deliberate choice. Entries with no list at all (created before the
        # confirm step existed) and entries holding exactly the old default set
        # are opted into every sensor; any other list was a deselection the
        # user made by hand, so it is carried over untouched.
        if stored is None or set(stored) == PREVIOUS_DEFAULT_SENSOR_KEYS:
            enabled_keys = [description.key for description in SENSOR_DESCRIPTIONS]
        else:
            enabled_keys = list(stored)

        # Runs before async_setup_entry, so no update listener is registered
        # yet and this cannot reload an entry that is still setting up.
        hass.config_entries.async_update_entry(
            entry,
            data={**entry.data, CONF_ENABLED_SENSORS: enabled_keys},
            minor_version=2,
        )

    return True
