"""Binary sensor platform for Open-Meteo Marine Weather.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""

from __future__ import annotations

from homeassistant.components.binary_sensor import BinarySensorEntity
from homeassistant.core import HomeAssistant
from homeassistant.helpers.entity_platform import AddEntitiesCallback
from homeassistant.helpers.update_coordinator import CoordinatorEntity

from . import MarineWeatherConfigEntry
from .coordinator import MarineWeatherCoordinator
from .entity import build_device_info
from .surf_score import DEFAULT_SURF_OPTIONS, score_conditions


async def async_setup_entry(
    hass: HomeAssistant,
    entry: MarineWeatherConfigEntry,
    async_add_entities: AddEntitiesCallback,
) -> None:
    """Set up the good-surf binary sensor from a config entry."""
    async_add_entities([GoodSurfBinarySensor(entry.runtime_data, entry)])


class GoodSurfBinarySensor(
    CoordinatorEntity[MarineWeatherCoordinator], BinarySensorEntity
):
    """On when current conditions meet the configured surf-quality thresholds."""

    _attr_has_entity_name = True
    _attr_translation_key = "good_surf"
    _attr_icon = "mdi:surfing"

    def __init__(
        self, coordinator: MarineWeatherCoordinator, entry: MarineWeatherConfigEntry
    ) -> None:
        """Initialize the good-surf binary sensor."""
        super().__init__(coordinator)
        self._attr_unique_id = f"{entry.unique_id}_good_surf"
        self._attr_device_info = build_device_info(entry)
        self._options = {**DEFAULT_SURF_OPTIONS, **entry.options}

    @property
    def is_on(self) -> bool | None:
        """Return True if current conditions meet the surf-quality thresholds."""
        if not self.coordinator.data:
            return None
        _rating, _score, meets_thresholds = score_conditions(
            self.coordinator.data, self._options
        )
        return meets_thresholds

    @property
    def extra_state_attributes(self) -> dict[str, object] | None:
        """Return the underlying rating and numeric score."""
        if not self.coordinator.data:
            return None
        rating, score, _meets = score_conditions(self.coordinator.data, self._options)
        return {"rating": rating, "score": score}
