"""Config flow for the Open-Meteo Marine Weather integration.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""

from __future__ import annotations

import logging
from typing import Any

import aiohttp
import voluptuous as vol

from homeassistant.config_entries import (
    ConfigEntry,
    ConfigFlow,
    ConfigFlowResult,
    OptionsFlow,
)
from homeassistant.const import CONF_NAME
from homeassistant.helpers import config_validation as cv
from homeassistant.helpers.aiohttp_client import async_get_clientsession

from .const import (
    API_TIMEOUT,
    API_URL,
    CONF_ENABLED_SENSORS,
    CONF_LATITUDE,
    CONF_LONGITUDE,
    CONF_MAX_CHOP_RATIO,
    CONF_MAX_WAVE_HEIGHT,
    CONF_MIN_PERIOD,
    CONF_MIN_WAVE_HEIGHT,
    CURRENT_VARIABLES,
    DOMAIN,
)
from .sensor import SENSOR_DESCRIPTIONS
from .surf_score import DEFAULT_SURF_OPTIONS

_LOGGER = logging.getLogger(__name__)


def _format_preview_value(value: Any, unit: str | None) -> str:
    """Format a sensor's current value for the confirm-step checkbox label."""
    if value is None:
        return "unknown"
    if unit:
        return f"{value} {unit}"
    return str(value)


class MarineWeatherConfigFlow(ConfigFlow, domain=DOMAIN):
    """Handle a config flow for Open-Meteo Marine Weather."""

    VERSION = 1

    @staticmethod
    def async_get_options_flow(
        config_entry: ConfigEntry,
    ) -> MarineWeatherOptionsFlow:
        """Create the options flow for tuning surf-quality thresholds."""
        return MarineWeatherOptionsFlow()

    def __init__(self) -> None:
        """Initialize the flow."""
        self._name: str | None = None
        self._latitude: float | None = None
        self._longitude: float | None = None
        self._current_data: dict[str, Any] = {}

    async def async_step_user(
        self, user_input: dict[str, Any] | None = None
    ) -> ConfigFlowResult:
        """Handle the initial step: name and coordinates."""
        errors: dict[str, str] = {}

        if user_input is not None:
            latitude = user_input[CONF_LATITUDE]
            longitude = user_input[CONF_LONGITUDE]

            # One entry per coordinate pair. Round to 4 decimal places
            # (~11m) so float-precision differences in re-entered
            # coordinates don't create duplicate entries for the same spot.
            await self.async_set_unique_id(f"{latitude:.4f}_{longitude:.4f}")
            self._abort_if_unique_id_configured()

            current_data, error = await self._async_fetch_current(latitude, longitude)
            if error:
                errors["base"] = error
            else:
                self._name = user_input[CONF_NAME]
                self._latitude = latitude
                self._longitude = longitude
                self._current_data = current_data or {}
                return await self.async_step_confirm()

        return self.async_show_form(
            step_id="user",
            data_schema=self._build_user_schema(user_input),
            errors=errors,
        )

    async def async_step_confirm(
        self, user_input: dict[str, Any] | None = None
    ) -> ConfigFlowResult:
        """Show each sensor's current value and let the user deselect any."""
        if user_input is not None:
            return self.async_create_entry(
                title=self._name,
                data={
                    CONF_NAME: self._name,
                    CONF_LATITUDE: self._latitude,
                    CONF_LONGITUDE: self._longitude,
                    CONF_ENABLED_SENSORS: user_input[CONF_ENABLED_SENSORS],
                },
            )

        sensor_options = {
            description.key: (
                f"{self._sensor_label(description.key)}: "
                f"{_format_preview_value(description.value_fn(self._current_data), description.native_unit_of_measurement)}"
            )
            for description in SENSOR_DESCRIPTIONS
        }

        return self.async_show_form(
            step_id="confirm",
            data_schema=vol.Schema(
                {
                    vol.Required(
                        CONF_ENABLED_SENSORS,
                        default=list(sensor_options),
                    ): cv.multi_select(sensor_options),
                }
            ),
            description_placeholders={CONF_NAME: self._name or ""},
        )

    def _sensor_label(self, key: str) -> str:
        """Human-readable sensor name, matching strings.json entity names."""
        if key.endswith("_name"):
            return f"{key[:-len('_name')].replace('_', ' ').capitalize()} (compass)"
        return key.replace("_", " ").capitalize()

    def _build_user_schema(self, user_input: dict[str, Any] | None) -> vol.Schema:
        """Build the user form schema, defaulting to the HA instance location."""
        suggested_name = (user_input or {}).get(CONF_NAME, "Marine Weather")
        suggested_lat = (user_input or {}).get(
            CONF_LATITUDE, self.hass.config.latitude
        )
        suggested_lon = (user_input or {}).get(
            CONF_LONGITUDE, self.hass.config.longitude
        )

        return vol.Schema(
            {
                vol.Required(CONF_NAME, default=suggested_name): str,
                vol.Required(
                    CONF_LATITUDE, default=suggested_lat
                ): vol.All(vol.Coerce(float), vol.Range(min=-90, max=90)),
                vol.Required(
                    CONF_LONGITUDE, default=suggested_lon
                ): vol.All(vol.Coerce(float), vol.Range(min=-180, max=180)),
            }
        )

    async def _async_fetch_current(
        self, latitude: float, longitude: float
    ) -> tuple[dict[str, Any] | None, str | None]:
        """Fetch current marine conditions from Open-Meteo.

        Returns (current_data, error_key). error_key is None on success.
        """
        session = async_get_clientsession(self.hass)
        params = {
            "latitude": latitude,
            "longitude": longitude,
            "current": ",".join(CURRENT_VARIABLES),
            "timezone": "auto",
            "models": "best_match",
        }

        try:
            async with session.get(
                API_URL,
                params=params,
                timeout=aiohttp.ClientTimeout(total=API_TIMEOUT),
            ) as response:
                if response.status == 429:
                    _LOGGER.debug("Open-Meteo rate limit exceeded (HTTP 429)")
                    return None, "cannot_connect"
                response.raise_for_status()
                data = await response.json()
        except TimeoutError as err:
            _LOGGER.debug("Timed out connecting to Open-Meteo: %s", err)
            return None, "cannot_connect"
        except aiohttp.ClientError as err:
            _LOGGER.debug("Cannot connect to Open-Meteo: %s", err)
            return None, "cannot_connect"

        # Open-Meteo returns wave data only for marine (coastal/ocean) points.
        # Inland coordinates yield an error object or a null current block.
        if data.get("error"):
            return None, "no_marine_data"
        current = data.get("current")
        if not isinstance(current, dict):
            return None, "no_marine_data"

        return current, None


class MarineWeatherOptionsFlow(OptionsFlow):
    """Let the user tune the surf-quality scoring thresholds."""

    async def async_step_init(
        self, user_input: dict[str, Any] | None = None
    ) -> ConfigFlowResult:
        """Show and save the surf-quality threshold form."""
        if user_input is not None:
            return self.async_create_entry(data=user_input)

        current = {**DEFAULT_SURF_OPTIONS, **self.config_entry.options}
        schema = vol.Schema(
            {
                vol.Required(
                    CONF_MIN_WAVE_HEIGHT, default=current[CONF_MIN_WAVE_HEIGHT]
                ): vol.All(vol.Coerce(float), vol.Range(min=0, max=10)),
                vol.Required(
                    CONF_MAX_WAVE_HEIGHT, default=current[CONF_MAX_WAVE_HEIGHT]
                ): vol.All(vol.Coerce(float), vol.Range(min=0, max=15)),
                vol.Required(
                    CONF_MIN_PERIOD, default=current[CONF_MIN_PERIOD]
                ): vol.All(vol.Coerce(float), vol.Range(min=1, max=30)),
                vol.Required(
                    CONF_MAX_CHOP_RATIO, default=current[CONF_MAX_CHOP_RATIO]
                ): vol.All(vol.Coerce(float), vol.Range(min=0.05, max=1.0)),
            }
        )
        return self.async_show_form(step_id="init", data_schema=schema)
