"""Constants for the Open-Meteo Marine Weather integration.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""

from __future__ import annotations

from datetime import timedelta

DOMAIN = "open_meteo_marine_weather"

API_URL = "https://marine-api.open-meteo.com/v1/marine"

# Bound how long a single request may hang before we give up and let the
# coordinator/config flow report a failure instead of blocking indefinitely.
API_TIMEOUT = 10

# Configuration keys
CONF_LATITUDE = "latitude"
CONF_LONGITUDE = "longitude"
CONF_ENABLED_SENSORS = "enabled_sensors"

# Options-flow keys for the surf-quality scoring thresholds.
CONF_MIN_WAVE_HEIGHT = "min_wave_height"
CONF_MAX_WAVE_HEIGHT = "max_wave_height"
CONF_MIN_PERIOD = "min_period"
CONF_MAX_CHOP_RATIO = "max_chop_ratio"

# Open-Meteo publishes marine data on an hourly cadence; polling more often
# than every 30 minutes wastes calls without gaining fresher data.
DEFAULT_SCAN_INTERVAL = timedelta(minutes=30)

# The "current" fields requested from the marine API.
CURRENT_VARIABLES = [
    "wave_height",
    "wave_direction",
    "wave_period",
    "wave_peak_period",
    "wind_wave_height",
    "wind_wave_direction",
    "wind_wave_period",
    "wind_wave_peak_period",
    "swell_wave_height",
    "swell_wave_direction",
    "swell_wave_period",
    "swell_wave_peak_period",
    "secondary_swell_wave_height",
    "secondary_swell_wave_direction",
    "secondary_swell_wave_period",
    "tertiary_swell_wave_height",
    "tertiary_swell_wave_direction",
    "tertiary_swell_wave_period",
    "sea_level_height_msl",
    "sea_surface_temperature",
    "ocean_current_velocity",
    "ocean_current_direction",
    "invert_barometer_height",
]

# The "daily" fields requested from the marine API, used to build the
# 7-day forecast attribute on each matching sensor.
DAILY_VARIABLES = [
    "wave_height_max",
    "wave_direction_dominant",
    "wave_period_max",
    "wind_wave_height_max",
    "wind_wave_direction_dominant",
    "wind_wave_period_max",
    "wind_wave_peak_period_max",
    "swell_wave_height_max",
    "swell_wave_direction_dominant",
    "swell_wave_period_max",
    "swell_wave_peak_period_max",
]

# Open-Meteo's default forecast_days is 7; state it explicitly so the
# request is not silently affected by a future API default change.
FORECAST_DAYS = 7

# The "hourly" fields requested from the marine API, used to build the
# hourly forecast attribute. Hourly uses the same variable names as
# "current" (no _max/_dominant suffix).
HOURLY_VARIABLES = list(CURRENT_VARIABLES)

# Number of hourly timesteps to request and expose. Kept small to avoid
# oversized state attributes and recorder growth; raise here to widen.
FORECAST_HOURS = 24
