"""Data update coordinator for Open-Meteo Marine Weather.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""

from __future__ import annotations

import logging

import aiohttp

from homeassistant.config_entries import ConfigEntry
from homeassistant.core import HomeAssistant
from homeassistant.helpers.aiohttp_client import async_get_clientsession
from homeassistant.helpers.update_coordinator import (
    DataUpdateCoordinator,
    UpdateFailed,
)

from .const import (
    API_URL,
    CONF_LATITUDE,
    CONF_LONGITUDE,
    CURRENT_VARIABLES,
    DAILY_VARIABLES,
    DEFAULT_SCAN_INTERVAL,
    DOMAIN,
    FORECAST_DAYS,
    FORECAST_HOURS,
    HOURLY_VARIABLES,
)

_LOGGER = logging.getLogger(__name__)


class MarineWeatherCoordinator(DataUpdateCoordinator[dict]):
    """Fetch marine weather data once and share it across all entities."""

    config_entry: ConfigEntry

    def __init__(self, hass: HomeAssistant, entry: ConfigEntry) -> None:
        """Initialize the coordinator."""
        self._session = async_get_clientsession(hass)
        self._latitude = entry.data[CONF_LATITUDE]
        self._longitude = entry.data[CONF_LONGITUDE]

        super().__init__(
            hass,
            _LOGGER,
            name=DOMAIN,
            update_interval=DEFAULT_SCAN_INTERVAL,
            config_entry=entry,
        )

    async def _async_update_data(self) -> dict:
        """Fetch the latest marine weather data from Open-Meteo."""
        params = {
            "latitude": self._latitude,
            "longitude": self._longitude,
            "current": ",".join(CURRENT_VARIABLES),
            "daily": ",".join(DAILY_VARIABLES),
            "hourly": ",".join(HOURLY_VARIABLES),
            "forecast_days": FORECAST_DAYS,
            "forecast_hours": FORECAST_HOURS,
            "timezone": "auto",
            "models": "best_match",
        }

        try:
            async with self._session.get(API_URL, params=params) as response:
                response.raise_for_status()
                data = await response.json()
        except aiohttp.ClientError as err:
            raise UpdateFailed(f"Error communicating with Open-Meteo: {err}") from err

        current = data.get("current")
        if not isinstance(current, dict):
            raise UpdateFailed("Open-Meteo response did not contain 'current' data")

        # Surface the resolved timezone alongside the readings so entities can
        # expose it without a second lookup.
        current["timezone"] = data.get("timezone")
        current["daily_forecast"] = self._parse_series(
            data.get("daily"), DAILY_VARIABLES, "date"
        )
        current["hourly_forecast"] = self._parse_series(
            data.get("hourly"), HOURLY_VARIABLES, "datetime"
        )
        return current

    @staticmethod
    def _parse_series(
        block: dict | None, variables: list[str], time_key: str
    ) -> list[dict]:
        """Reshape Open-Meteo's parallel arrays into one dict per timestep.

        Works for both the `daily` and `hourly` blocks, which share the same
        shape: a `time` array plus one parallel array per variable.
        """
        if not isinstance(block, dict):
            return []

        times = block.get("time")
        if not isinstance(times, list):
            return []

        return [
            {
                time_key: timestamp,
                **{
                    variable: block[variable][index]
                    for variable in variables
                    if isinstance(block.get(variable), list)
                    and index < len(block[variable])
                },
            }
            for index, timestamp in enumerate(times)
        ]
