"""Diagnostics support for Open-Meteo Marine Weather.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""

from __future__ import annotations

from typing import Any

from homeassistant.core import HomeAssistant

from . import MarineWeatherConfigEntry


async def async_get_config_entry_diagnostics(
    hass: HomeAssistant, entry: MarineWeatherConfigEntry
) -> dict[str, Any]:
    """Return diagnostics for a config entry.

    Latitude/longitude are not treated as sensitive for this integration
    (no account, no API key, no personal data), so nothing is redacted.
    """
    coordinator = entry.runtime_data

    return {
        "entry": {
            "title": entry.title,
            "unique_id": entry.unique_id,
            "data": dict(entry.data),
        },
        "coordinator": {
            "last_update_success": coordinator.last_update_success,
            "last_exception": repr(coordinator.last_exception)
            if coordinator.last_exception
            else None,
            "update_interval_seconds": (
                coordinator.update_interval.total_seconds()
                if coordinator.update_interval
                else None
            ),
        },
        "current_data": coordinator.data,
    }
