"""Shared entity helpers for Open-Meteo Marine Weather.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""

from __future__ import annotations

from homeassistant.helpers.device_registry import DeviceInfo

from . import MarineWeatherConfigEntry
from .const import DOMAIN


def build_device_info(entry: MarineWeatherConfigEntry) -> DeviceInfo:
    """Build the shared device block for every entity of this entry."""
    return DeviceInfo(
        identifiers={(DOMAIN, entry.unique_id)},
        name=entry.data.get("name") or entry.title,
        manufacturer="Open-Meteo",
        model="Marine Weather",
        entry_type=None,
        configuration_url="https://open-meteo.com/en/docs/marine-weather-api",
    )
