"""Number platform for Open-Meteo Marine Weather.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""

from __future__ import annotations

from homeassistant.components.number import (
    NumberEntity,
    NumberEntityDescription,
    NumberMode,
)
from homeassistant.const import UnitOfLength, UnitOfTime
from homeassistant.core import HomeAssistant
from homeassistant.helpers.entity import EntityCategory
from homeassistant.helpers.entity_platform import AddEntitiesCallback

from . import MarineWeatherConfigEntry
from .const import (
    CONF_MAX_CHOP_RATIO,
    CONF_MAX_WAVE_HEIGHT,
    CONF_MIN_PERIOD,
    CONF_MIN_WAVE_HEIGHT,
)
from .entity import build_device_info
from .surf_score import DEFAULT_SURF_OPTIONS

# Ranges mirror the bounds the options flow used to validate against, so a
# value set here is always one score_conditions() can work with.
THRESHOLD_DESCRIPTIONS: tuple[NumberEntityDescription, ...] = (
    NumberEntityDescription(
        key=CONF_MIN_WAVE_HEIGHT,
        translation_key="min_wave_height",
        entity_category=EntityCategory.CONFIG,
        mode=NumberMode.BOX,
        native_min_value=0,
        native_max_value=10,
        native_step=0.1,
        native_unit_of_measurement=UnitOfLength.METERS,
    ),
    NumberEntityDescription(
        key=CONF_MAX_WAVE_HEIGHT,
        translation_key="max_wave_height",
        entity_category=EntityCategory.CONFIG,
        mode=NumberMode.BOX,
        native_min_value=0,
        native_max_value=15,
        native_step=0.1,
        native_unit_of_measurement=UnitOfLength.METERS,
    ),
    NumberEntityDescription(
        key=CONF_MIN_PERIOD,
        translation_key="min_period",
        entity_category=EntityCategory.CONFIG,
        mode=NumberMode.BOX,
        native_min_value=1,
        native_max_value=30,
        native_step=0.5,
        native_unit_of_measurement=UnitOfTime.SECONDS,
    ),
    NumberEntityDescription(
        key=CONF_MAX_CHOP_RATIO,
        translation_key="max_chop_ratio",
        entity_category=EntityCategory.CONFIG,
        mode=NumberMode.BOX,
        native_min_value=0.05,
        native_max_value=1.0,
        native_step=0.05,
    ),
)


async def async_setup_entry(
    hass: HomeAssistant,
    entry: MarineWeatherConfigEntry,
    async_add_entities: AddEntitiesCallback,
) -> None:
    """Set up the surf-quality threshold controls from a config entry."""
    async_add_entities(
        SurfThresholdNumber(entry, description)
        for description in THRESHOLD_DESCRIPTIONS
    )


class SurfThresholdNumber(NumberEntity):
    """A surf-quality threshold, stored in the config entry's options."""

    _attr_has_entity_name = True
    _attr_icon = "mdi:tune-variant"

    def __init__(
        self,
        entry: MarineWeatherConfigEntry,
        description: NumberEntityDescription,
    ) -> None:
        """Initialize the threshold control."""
        self.entity_description = description
        self._entry = entry
        self._attr_unique_id = f"{entry.unique_id}_{description.key}"
        self._attr_device_info = build_device_info(entry)

    @property
    def native_value(self) -> float:
        """Return the current threshold, read live from the config entry."""
        key = self.entity_description.key
        return self._entry.options.get(key, DEFAULT_SURF_OPTIONS[key])

    async def async_set_native_value(self, value: float) -> None:
        """Store the new threshold and refresh the entities that use it."""
        self.hass.config_entries.async_update_entry(
            self._entry,
            options={**self._entry.options, self.entity_description.key: value},
        )
        # The rating sensor and good-surf binary sensor read the thresholds
        # live, so a listener nudge is enough to re-render them; reloading the
        # entry would recreate every entity, including this one.
        self._entry.runtime_data.async_update_listeners()
        self.async_write_ha_state()
