"""Sensor platform for Open-Meteo Marine Weather.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass

from homeassistant.components.sensor import (
    SensorDeviceClass,
    SensorEntity,
    SensorEntityDescription,
    SensorStateClass,
)
from homeassistant.const import (
    DEGREE,
    UnitOfLength,
    UnitOfSpeed,
    UnitOfTemperature,
    UnitOfTime,
)
from homeassistant.core import HomeAssistant
from homeassistant.helpers.entity_platform import AddEntitiesCallback
from homeassistant.helpers.update_coordinator import CoordinatorEntity

from . import MarineWeatherConfigEntry
from .const import CONF_ENABLED_SENSORS, CONF_LATITUDE, CONF_LONGITUDE, DOMAIN
from .coordinator import MarineWeatherCoordinator
from .entity import build_device_info
from .surf_score import (
    DEFAULT_SURF_OPTIONS,
    SURF_RATINGS,
    best_upcoming_window,
    score_conditions,
)

COMPASS_DIRECTIONS = [
    "N", "NNE", "NE", "ENE", "E", "ESE", "SE", "SSE",
    "S", "SSW", "SW", "WSW", "W", "WNW", "NW", "NNW",
]


def degrees_to_compass(degrees: float | None) -> str | None:
    """Convert a bearing in degrees to a 16-point compass direction."""
    if degrees is None:
        return None
    return COMPASS_DIRECTIONS[round(degrees / 22.5) % 16]


@dataclass(frozen=True, kw_only=True)
class MarineSensorDescription(SensorEntityDescription):
    """Describes a marine weather sensor."""

    value_fn: Callable[[dict], float | str | None]
    # Matching key in each daily-forecast entry, e.g. "wave_height_max".
    # None for sensors with no daily equivalent.
    daily_key: str | None = None
    # Matching key in each hourly-forecast entry. None for derived sensors
    # that do not come directly from an Open-Meteo hourly variable.
    hourly_key: str | None = None


SENSOR_DESCRIPTIONS: tuple[MarineSensorDescription, ...] = (
    MarineSensorDescription(
        key="wave_height",
        translation_key="wave_height",
        device_class=SensorDeviceClass.DISTANCE,
        native_unit_of_measurement=UnitOfLength.METERS,
        state_class=SensorStateClass.MEASUREMENT,
        value_fn=lambda data: data.get("wave_height"),
        daily_key="wave_height_max",
    ),
    MarineSensorDescription(
        key="wave_direction",
        translation_key="wave_direction",
        native_unit_of_measurement=DEGREE,
        value_fn=lambda data: data.get("wave_direction"),
        daily_key="wave_direction_dominant",
    ),
    MarineSensorDescription(
        key="wave_direction_name",
        translation_key="wave_direction_name",
        value_fn=lambda data: degrees_to_compass(data.get("wave_direction")),
    ),
    MarineSensorDescription(
        key="wave_period",
        translation_key="wave_period",
        device_class=SensorDeviceClass.DURATION,
        native_unit_of_measurement=UnitOfTime.SECONDS,
        state_class=SensorStateClass.MEASUREMENT,
        value_fn=lambda data: data.get("wave_period"),
        daily_key="wave_period_max",
    ),
    MarineSensorDescription(
        key="wave_peak_period",
        translation_key="wave_peak_period",
        device_class=SensorDeviceClass.DURATION,
        native_unit_of_measurement=UnitOfTime.SECONDS,
        state_class=SensorStateClass.MEASUREMENT,
        value_fn=lambda data: data.get("wave_peak_period"),
        hourly_key="wave_peak_period",
    ),
    MarineSensorDescription(
        key="swell_wave_height",
        translation_key="swell_wave_height",
        device_class=SensorDeviceClass.DISTANCE,
        native_unit_of_measurement=UnitOfLength.METERS,
        state_class=SensorStateClass.MEASUREMENT,
        value_fn=lambda data: data.get("swell_wave_height"),
        daily_key="swell_wave_height_max",
    ),
    MarineSensorDescription(
        key="swell_wave_direction",
        translation_key="swell_wave_direction",
        native_unit_of_measurement=DEGREE,
        value_fn=lambda data: data.get("swell_wave_direction"),
        daily_key="swell_wave_direction_dominant",
    ),
    MarineSensorDescription(
        key="swell_wave_direction_name",
        translation_key="swell_wave_direction_name",
        value_fn=lambda data: degrees_to_compass(data.get("swell_wave_direction")),
    ),
    MarineSensorDescription(
        key="swell_wave_period",
        translation_key="swell_wave_period",
        device_class=SensorDeviceClass.DURATION,
        native_unit_of_measurement=UnitOfTime.SECONDS,
        state_class=SensorStateClass.MEASUREMENT,
        value_fn=lambda data: data.get("swell_wave_period"),
        daily_key="swell_wave_period_max",
    ),
    MarineSensorDescription(
        key="swell_wave_peak_period",
        translation_key="swell_wave_peak_period",
        device_class=SensorDeviceClass.DURATION,
        native_unit_of_measurement=UnitOfTime.SECONDS,
        state_class=SensorStateClass.MEASUREMENT,
        value_fn=lambda data: data.get("swell_wave_peak_period"),
        daily_key="swell_wave_peak_period_max",
    ),
    MarineSensorDescription(
        key="secondary_swell_wave_height",
        translation_key="secondary_swell_wave_height",
        device_class=SensorDeviceClass.DISTANCE,
        native_unit_of_measurement=UnitOfLength.METERS,
        state_class=SensorStateClass.MEASUREMENT,
        value_fn=lambda data: data.get("secondary_swell_wave_height"),
        hourly_key="secondary_swell_wave_height",
    ),
    MarineSensorDescription(
        key="secondary_swell_wave_direction",
        translation_key="secondary_swell_wave_direction",
        native_unit_of_measurement=DEGREE,
        value_fn=lambda data: data.get("secondary_swell_wave_direction"),
        hourly_key="secondary_swell_wave_direction",
    ),
    MarineSensorDescription(
        key="secondary_swell_wave_direction_name",
        translation_key="secondary_swell_wave_direction_name",
        value_fn=lambda data: degrees_to_compass(
            data.get("secondary_swell_wave_direction")
        ),
    ),
    MarineSensorDescription(
        key="secondary_swell_wave_period",
        translation_key="secondary_swell_wave_period",
        device_class=SensorDeviceClass.DURATION,
        native_unit_of_measurement=UnitOfTime.SECONDS,
        state_class=SensorStateClass.MEASUREMENT,
        value_fn=lambda data: data.get("secondary_swell_wave_period"),
        hourly_key="secondary_swell_wave_period",
    ),
    MarineSensorDescription(
        key="wind_wave_height",
        translation_key="wind_wave_height",
        device_class=SensorDeviceClass.DISTANCE,
        native_unit_of_measurement=UnitOfLength.METERS,
        state_class=SensorStateClass.MEASUREMENT,
        value_fn=lambda data: data.get("wind_wave_height"),
        daily_key="wind_wave_height_max",
    ),
    MarineSensorDescription(
        key="wind_wave_direction",
        translation_key="wind_wave_direction",
        native_unit_of_measurement=DEGREE,
        value_fn=lambda data: data.get("wind_wave_direction"),
        daily_key="wind_wave_direction_dominant",
    ),
    MarineSensorDescription(
        key="wind_wave_period",
        translation_key="wind_wave_period",
        device_class=SensorDeviceClass.DURATION,
        native_unit_of_measurement=UnitOfTime.SECONDS,
        state_class=SensorStateClass.MEASUREMENT,
        value_fn=lambda data: data.get("wind_wave_period"),
        daily_key="wind_wave_period_max",
    ),
    MarineSensorDescription(
        key="wind_wave_peak_period",
        translation_key="wind_wave_peak_period",
        device_class=SensorDeviceClass.DURATION,
        native_unit_of_measurement=UnitOfTime.SECONDS,
        state_class=SensorStateClass.MEASUREMENT,
        value_fn=lambda data: data.get("wind_wave_peak_period"),
        daily_key="wind_wave_peak_period_max",
    ),
    MarineSensorDescription(
        key="sea_level_height_msl",
        translation_key="sea_level_height_msl",
        device_class=SensorDeviceClass.DISTANCE,
        native_unit_of_measurement=UnitOfLength.METERS,
        state_class=SensorStateClass.MEASUREMENT,
        value_fn=lambda data: data.get("sea_level_height_msl"),
        hourly_key="sea_level_height_msl",
    ),
    MarineSensorDescription(
        key="sea_surface_temperature",
        translation_key="sea_surface_temperature",
        device_class=SensorDeviceClass.TEMPERATURE,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        state_class=SensorStateClass.MEASUREMENT,
        value_fn=lambda data: data.get("sea_surface_temperature"),
        hourly_key="sea_surface_temperature",
    ),
    MarineSensorDescription(
        key="ocean_current_velocity",
        translation_key="ocean_current_velocity",
        device_class=SensorDeviceClass.SPEED,
        native_unit_of_measurement=UnitOfSpeed.KILOMETERS_PER_HOUR,
        state_class=SensorStateClass.MEASUREMENT,
        value_fn=lambda data: data.get("ocean_current_velocity"),
        hourly_key="ocean_current_velocity",
    ),
    MarineSensorDescription(
        key="ocean_current_direction",
        translation_key="ocean_current_direction",
        native_unit_of_measurement=DEGREE,
        value_fn=lambda data: data.get("ocean_current_direction"),
        hourly_key="ocean_current_direction",
    ),
    MarineSensorDescription(
        key="ocean_current_direction_name",
        translation_key="ocean_current_direction_name",
        value_fn=lambda data: degrees_to_compass(data.get("ocean_current_direction")),
    ),
    MarineSensorDescription(
        key="tertiary_swell_wave_height",
        translation_key="tertiary_swell_wave_height",
        device_class=SensorDeviceClass.DISTANCE,
        native_unit_of_measurement=UnitOfLength.METERS,
        state_class=SensorStateClass.MEASUREMENT,
        value_fn=lambda data: data.get("tertiary_swell_wave_height"),
        hourly_key="tertiary_swell_wave_height",
    ),
    MarineSensorDescription(
        key="tertiary_swell_wave_direction",
        translation_key="tertiary_swell_wave_direction",
        native_unit_of_measurement=DEGREE,
        value_fn=lambda data: data.get("tertiary_swell_wave_direction"),
        hourly_key="tertiary_swell_wave_direction",
    ),
    MarineSensorDescription(
        key="tertiary_swell_wave_direction_name",
        translation_key="tertiary_swell_wave_direction_name",
        value_fn=lambda data: degrees_to_compass(
            data.get("tertiary_swell_wave_direction")
        ),
    ),
    MarineSensorDescription(
        key="tertiary_swell_wave_period",
        translation_key="tertiary_swell_wave_period",
        device_class=SensorDeviceClass.DURATION,
        native_unit_of_measurement=UnitOfTime.SECONDS,
        state_class=SensorStateClass.MEASUREMENT,
        value_fn=lambda data: data.get("tertiary_swell_wave_period"),
        hourly_key="tertiary_swell_wave_period",
    ),
    MarineSensorDescription(
        key="invert_barometer_height",
        translation_key="invert_barometer_height",
        device_class=SensorDeviceClass.DISTANCE,
        native_unit_of_measurement=UnitOfLength.METERS,
        state_class=SensorStateClass.MEASUREMENT,
        value_fn=lambda data: data.get("invert_barometer_height"),
        hourly_key="invert_barometer_height",
    ),
)

PREVIOUS_DEFAULT_SENSOR_KEYS = {
    "wave_height",
    "wave_direction",
    "wave_direction_name",
    "wave_period",
    "swell_wave_height",
    "swell_wave_direction",
    "swell_wave_direction_name",
    "swell_wave_period",
    "swell_wave_peak_period",
    "wind_wave_height",
    "wind_wave_direction",
    "wind_wave_period",
    "wind_wave_peak_period",
}


async def async_setup_entry(
    hass: HomeAssistant,
    entry: MarineWeatherConfigEntry,
    async_add_entities: AddEntitiesCallback,
) -> None:
    """Set up marine weather sensors from a config entry."""
    coordinator = entry.runtime_data

    # Entries created before the sensor-selection confirm step existed have no
    # CONF_ENABLED_SENSORS key. Entries with the previous full default set get
    # newly added sensors automatically, while custom subsets stay unchanged.
    all_sensor_keys = [description.key for description in SENSOR_DESCRIPTIONS]
    enabled_keys = entry.data.get(CONF_ENABLED_SENSORS, all_sensor_keys)
    if (
        CONF_ENABLED_SENSORS in entry.data
        and PREVIOUS_DEFAULT_SENSOR_KEYS.issubset(enabled_keys)
        and set(enabled_keys) != set(all_sensor_keys)
    ):
        enabled_keys = [
            *enabled_keys,
            *(key for key in all_sensor_keys if key not in enabled_keys),
        ]
        hass.config_entries.async_update_entry(
            entry,
            data={**entry.data, CONF_ENABLED_SENSORS: enabled_keys},
        )

    async_add_entities(
        [
            *(
                MarineWeatherSensor(coordinator, entry, description)
                for description in SENSOR_DESCRIPTIONS
                if description.key in enabled_keys
            ),
            # Always added: a derived feature, not a raw passthrough sensor,
            # so it does not go through the enabled_sensors opt-in checkbox.
            SurfRatingSensor(coordinator, entry),
        ]
    )


class MarineWeatherSensor(
    CoordinatorEntity[MarineWeatherCoordinator], SensorEntity
):
    """A single marine weather measurement backed by the shared coordinator."""

    entity_description: MarineSensorDescription
    _attr_has_entity_name = True
    _attr_icon = "mdi:waves"

    def __init__(
        self,
        coordinator: MarineWeatherCoordinator,
        entry: MarineWeatherConfigEntry,
        description: MarineSensorDescription,
    ) -> None:
        """Initialize the sensor."""
        super().__init__(coordinator)
        self.entity_description = description
        self._attr_unique_id = f"{entry.unique_id}_{description.key}"
        self._attr_device_info = build_device_info(entry)

    @property
    def native_value(self) -> float | str | None:
        """Return the current value of the sensor."""
        if not self.coordinator.data:
            return None
        return self.entity_description.value_fn(self.coordinator.data)

    @property
    def extra_state_attributes(self) -> dict[str, list[dict]] | None:
        """Return the daily and hourly forecast for this variable, if any.

        Derived compass-name sensors have no direct Open-Meteo forecast
        variable and expose no forecast attributes.
        """
        key = self.entity_description.key
        if not self.coordinator.data:
            return None

        daily_key = self.entity_description.daily_key
        hourly_key = self.entity_description.hourly_key
        if hourly_key is None and daily_key is not None:
            hourly_key = key
        if daily_key is None and hourly_key is None:
            return None

        daily_forecast = self.coordinator.data.get("daily_forecast", [])
        hourly_forecast = self.coordinator.data.get("hourly_forecast", [])
        attributes: dict[str, list[dict]] = {}
        if daily_key is not None:
            attributes["forecast"] = [
                {"date": day["date"], key: day.get(daily_key)}
                for day in daily_forecast
            ]
        if hourly_key is not None:
            attributes["hourly_forecast"] = [
                {"datetime": hour["datetime"], key: hour.get(hourly_key)}
                for hour in hourly_forecast
            ]
        return attributes


class SurfRatingSensor(CoordinatorEntity[MarineWeatherCoordinator], SensorEntity):
    """Derived Poor/Fair/Good/Epic surf-quality rating for this location."""

    _attr_has_entity_name = True
    _attr_translation_key = "surf_rating"
    _attr_icon = "mdi:surfing"
    _attr_device_class = SensorDeviceClass.ENUM
    _attr_options = SURF_RATINGS

    def __init__(
        self, coordinator: MarineWeatherCoordinator, entry: MarineWeatherConfigEntry
    ) -> None:
        """Initialize the surf rating sensor."""
        super().__init__(coordinator)
        self._attr_unique_id = f"{entry.unique_id}_surf_rating"
        self._attr_device_info = build_device_info(entry)
        self._options = {**DEFAULT_SURF_OPTIONS, **entry.options}

    @property
    def native_value(self) -> str | None:
        """Return the current surf-quality rating."""
        if not self.coordinator.data:
            return None
        rating, _score, _meets = score_conditions(self.coordinator.data, self._options)
        return rating

    @property
    def extra_state_attributes(self) -> dict[str, object] | None:
        """Return the numeric score and the best upcoming hours."""
        if not self.coordinator.data:
            return None
        _rating, score, _meets = score_conditions(self.coordinator.data, self._options)
        hourly_forecast = self.coordinator.data.get("hourly_forecast", [])
        return {
            "score": score,
            "next_good_window": best_upcoming_window(hourly_forecast, self._options),
        }
