"""Shared surf-quality scoring for Open-Meteo Marine Weather.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""

from __future__ import annotations

from typing import TypedDict


class SurfOptions(TypedDict):
    """User-tunable thresholds that parameterize the surf-quality heuristic."""

    min_wave_height: float
    max_wave_height: float
    min_period: float
    max_chop_ratio: float


DEFAULT_SURF_OPTIONS: SurfOptions = {
    "min_wave_height": 0.8,
    "max_wave_height": 2.0,
    "min_period": 8.0,
    "max_chop_ratio": 0.5,
}

RATING_POOR = "poor"
RATING_FAIR = "fair"
RATING_GOOD = "good"
RATING_EPIC = "epic"
SURF_RATINGS = [RATING_POOR, RATING_FAIR, RATING_GOOD, RATING_EPIC]


def score_conditions(
    data: dict, options: SurfOptions
) -> tuple[str, float, bool]:
    """Score a single set of marine conditions.

    Accepts either the coordinator's "current" dict or one entry from its
    "hourly_forecast" list; both use the same variable names.

    Returns (rating, numeric_score 0-100, meets_thresholds).
    """
    wave_height = data.get("wave_height")
    period = data.get("swell_wave_period") or data.get("wave_period")
    wind_wave_height = data.get("wind_wave_height") or 0.0
    swell_wave_height = data.get("swell_wave_height")

    if wave_height is None or period is None:
        return RATING_POOR, 0.0, False

    lo = options["min_wave_height"]
    hi = options["max_wave_height"]
    mid = (lo + hi) / 2
    half_range = max(hi - lo, 0.01) / 2
    if lo <= wave_height <= hi:
        height_score = 40 * (1 - abs(wave_height - mid) / half_range)
    elif wave_height < lo:
        height_score = 40 * max(0.0, wave_height / lo) * 0.5
    else:
        height_score = 40 * max(0.0, 1 - (wave_height - hi) / hi) * 0.5

    # Ramp up to full credit 6s above min_period; below min_period, taper down
    # to 0 by half of min_period instead of hard-flooring at the threshold,
    # so a period just under the target isn't scored the same as dead flat.
    min_period = options["min_period"]
    if period >= min_period:
        period_score = 35 * min(1.0, (period - min_period) / 6.0)
    else:
        period_score = 35 * max(0.0, period / min_period - 0.5) / 0.5

    # Symmetric taper for chop: full credit at ratio 0, zero credit at
    # 2x the configured max_ratio, instead of cliffing to 0 exactly at
    # max_ratio (a spot just over the threshold isn't fully blown out).
    total_height = swell_wave_height if swell_wave_height else wave_height
    chop_ratio = wind_wave_height / total_height if total_height else 1.0
    max_ratio = options["max_chop_ratio"]
    chop_score = (
        25 * max(0.0, 1 - chop_ratio / (2 * max_ratio)) if max_ratio > 0 else 0.0
    )

    score = height_score + period_score + chop_score
    meets_thresholds = (
        lo <= wave_height <= hi
        and period >= min_period
        and chop_ratio <= max_ratio
    )

    if score >= 75:
        rating = RATING_EPIC
    elif score >= 55:
        rating = RATING_GOOD
    elif score >= 35:
        rating = RATING_FAIR
    else:
        rating = RATING_POOR

    return rating, round(score, 1), meets_thresholds


def best_upcoming_window(
    hourly_forecast: list[dict], options: SurfOptions, top_n: int = 3
) -> list[dict]:
    """Score each hourly forecast entry and return the top_n best hours."""
    scored = []
    for hour in hourly_forecast:
        rating, score, meets = score_conditions(hour, options)
        scored.append(
            {
                "datetime": hour.get("datetime"),
                "rating": rating,
                "score": score,
                "meets_thresholds": meets,
            }
        )
    scored.sort(key=lambda entry: entry["score"], reverse=True)
    return scored[:top_n]
